# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        go get -u golang.org/x/lint/golint
        golint -set_exit_status ./...

    - name: Install dependencies
      run: | 
        go get github.com/go-chi/chi/v5 
        go get github.com/onsi/ginkgo/v2
        go get github.com/onsi/gomega/...
        go get github.com/spf13/viper
        go get github.com/thedevsaddam/renderer
        go get gorm.io/driver/postgres
        go get gorm.io/gorm

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
