# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest

    env:
      GOPATH: ${{ github.workspace }}
      GOBIN: ${{ github.workspace }}/bin
    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/src/web-api-go
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
        path: ${{ env.GOPATH }}/src/web-api-go

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20.4
        cache-dependency-path: subdir/go.sum

    - name: Install dependencies
      run: |
        go version
        go get -u golang.org/x/lint/golint
        go get -u github.com/go-chi/chi/v5 
        go get -u github.com/onsi/ginkgo/v2
        go get -u github.com/onsi/gomega/...
        go get -u github.com/spf13/viper
        go get -u github.com/thedevsaddam/renderer
        go get -u gorm.io/driver/postgres
        go get -u gorm.io/gorm

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Run golangci-lint
      # You may pin to the exact commit or the version.
      # uses: golangci/golangci-lint-action@08e2f20817b15149a52b5b3ebe7de50aff2ba8c5
      uses: golangci/golangci-lint-action@v3.4.0
      with:
        # version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
        version: latest
        # golangci-lint command line arguments