# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest

    env:
      GOPATH: ${{ github.workspace }}
      GOBIN: ${{ github.workspace }}/bin
    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/src/web-api-go
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
        path: ${{ env.GOPATH }}/src/web-api-go

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20.4

    - name: Install dependencies
      run: |
        go version
        go get -u golang.org/x/lint/golint
        go get -u github.com/go-chi/chi/v5 
        go get -u github.com/onsi/ginkgo/v2
        go get -u github.com/onsi/gomega/...
        go get -u github.com/spf13/viper
        go get -u github.com/thedevsaddam/renderer
        go get -u gorm.io/driver/postgres
        go get -u gorm.io/gorm

    - name: Build
      run: go build -v ./...

    - name: Lint
      run: |
        go vet .
        golint .

    - name: Test
      run: go test -v ./...
